export interface StandortData {
  slug: string;
  city: string;
  isHauptstandort?: boolean;
  metaTitle: string;
  metaDescription: string;
  heroSubline: string;
  trustText: string;
  description: string;
  einsatzgebiete: { city: string; time: string }[];
  faqs: { q: string; a: string }[];
}

export const STANDORTE: StandortData[] = [
  {
    slug: 'euskirchen',
    city: 'Euskirchen',
    isHauptstandort: true,
    metaTitle: 'KFZ Gutachter Euskirchen – Unser Hauptstandort | UnfallExperten NRW',
    metaDescription: 'Ihr KFZ Gutachter in Euskirchen – unser Hauptstandort. Kostenlose Unfallgutachten, schnelle Termine und persönliche Betreuung. Jetzt anrufen!',
    heroSubline: 'Von unserem Hauptstandort in Euskirchen aus sind wir blitzschnell bei Ihnen – professionelle Unfallgutachten & Schadensbewertung in Euskirchen und der gesamten Region.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'Euskirchen ist unser Hauptstandort und das Herzstück unserer täglichen Arbeit. Von hier aus koordinieren wir Gutachtertermine in der gesamten Region und sind meist innerhalb kürzester Zeit vor Ort. Ob direkt in Euskirchen, in der Voreifel oder im weiteren Umkreis – wir kommen zu Ihnen ans Fahrzeug, egal wo es steht. Unsere Sachverständigen kennen die Region wie ihre Westentasche und sorgen dafür, dass Ihr Gutachten schnell, gründlich und rechtssicher erstellt wird. Stressfrei und ohne Kosten für Sie als Geschädigten.',
    einsatzgebiete: [
      { city: 'Mechernich', time: 'ca. 15 Min' },
      { city: 'Zülpich', time: 'ca. 15 Min' },
      { city: 'Bad Münstereifel', time: 'ca. 10 Min' },
      { city: 'Weilerswist', time: 'ca. 15 Min' },
      { city: 'Rheinbach', time: 'ca. 20 Min' },
      { city: 'Swisttal', time: 'ca. 25 Min' },
      { city: 'Erftstadt', time: 'ca. 25 Min' },
      { city: 'Bonn', time: 'ca. 35 Min' },
      { city: 'Köln', time: 'ca. 45 Min' },
      { city: 'Meckenheim', time: 'ca. 20 Min' },
      { city: 'Alfter', time: 'ca. 25 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein Gutachten in Euskirchen?', a: 'Für Geschädigte bei einem unverschuldeten Unfall ist unser Gutachten komplett kostenlos. Die Kosten trägt die gegnerische Versicherung. Sie gehen keinerlei finanzielles Risiko ein.' },
      { q: 'Wie schnell sind Sie in Euskirchen vor Ort?', a: 'Da Euskirchen unser Hauptstandort ist, sind wir in der Regel innerhalb weniger Minuten bei Ihnen. In den meisten Fällen können wir noch am selben Tag einen Termin anbieten.' },
      { q: 'Wer übernimmt die Kosten nach einem Unfall?', a: 'Bei einem unverschuldeten Unfall zahlt die Haftpflichtversicherung des Unfallverursachers sämtliche Gutachterkosten. Für Sie entstehen keine Kosten.' },
      { q: 'Kann ich Sie direkt kontaktieren?', a: 'Selbstverständlich. Sie erreichen uns telefonisch, per WhatsApp oder über unser Kontaktformular. Wir antworten in der Regel innerhalb von 15 Minuten.' },
      { q: 'Wie läuft ein Gutachten ab?', a: 'Nach Ihrer Kontaktaufnahme vereinbaren wir einen Termin, begutachten Ihr Fahrzeug vor Ort und erstellen das Gutachten innerhalb von 24–72 Stunden. Anschließend wird es direkt an die Versicherung übermittelt.' },
    ],
  },
  {
    slug: 'bonn',
    city: 'Bonn',
    metaTitle: 'KFZ Gutachter Bonn – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Bonn gesucht? Kostenlose Unfallgutachten für Geschädigte – schnell vor Ort, unabhängig und zuverlässig. Jetzt Kontakt aufnehmen!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Bonn und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'Als unabhängige Gutachter-Experten sind wir regelmäßig in Bonn und dem gesamten Stadtgebiet im Einsatz. Ob in Bad Godesberg, Beuel oder der Bonner Innenstadt – wir kommen direkt zu Ihrem Fahrzeug. Dank unserer kurzen Anfahrtswege garantieren wir schnelle Termine, oft noch am selben Tag. Unser Anspruch: eine reibungslose Abwicklung ohne unnötige Wartezeiten, damit Sie sich nach dem Unfall auf das Wesentliche konzentrieren können.',
    einsatzgebiete: [
      { city: 'Bonn-Bad Godesberg', time: 'ca. 15 Min' },
      { city: 'Bonn-Beuel', time: 'ca. 15 Min' },
      { city: 'Köln', time: 'ca. 30 Min' },
      { city: 'Siegburg', time: 'ca. 20 Min' },
      { city: 'Sankt Augustin', time: 'ca. 15 Min' },
      { city: 'Troisdorf', time: 'ca. 25 Min' },
      { city: 'Königswinter', time: 'ca. 20 Min' },
      { city: 'Bornheim', time: 'ca. 15 Min' },
      { city: 'Alfter', time: 'ca. 10 Min' },
      { city: 'Meckenheim', time: 'ca. 20 Min' },
      { city: 'Rheinbach', time: 'ca. 25 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein KFZ-Gutachten in Bonn?', a: 'Für Geschädigte bei einem unverschuldeten Unfall ist das Gutachten komplett kostenlos. Die gegnerische Versicherung übernimmt alle Kosten.' },
      { q: 'Wie schnell kommen Sie nach Bonn?', a: 'Wir sind in der Regel innerhalb von 20 Minuten in Bonn vor Ort. In vielen Fällen können wir noch am selben Tag einen Termin vereinbaren.' },
      { q: 'Wer bezahlt den Gutachter nach einem Unfall?', a: 'Die Haftpflichtversicherung des Unfallverursachers trägt die Gutachterkosten. Für Sie als Geschädigten fallen keine Kosten an.' },
      { q: 'Muss ich zum Gutachter fahren?', a: 'Nein, wir kommen zu Ihnen – zum Unfallort, nach Hause oder zur Arbeit. Überall in Bonn und Umgebung.' },
      { q: 'Wie läuft die Begutachtung ab?', a: 'Nach Ihrem Anruf vereinbaren wir einen schnellen Termin. Wir dokumentieren den Schaden vor Ort und erstellen das Gutachten innerhalb von 24–72 Stunden.' },
    ],
  },
  {
    slug: 'koeln',
    city: 'Köln',
    metaTitle: 'KFZ Gutachter Köln – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Köln – kostenlose Unfallgutachten für Geschädigte. Schnell vor Ort in allen Kölner Stadtteilen. Jetzt anrufen!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Köln und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'In der Millionenstadt Köln sind wir als Ihre regionalen Gutachter-Experten täglich unterwegs. Ob Ehrenfeld, Nippes, Porz oder Lindenthal – unser Team kennt jeden Stadtteil und ist flexibel einsetzbar. Wir wissen, dass nach einem Unfall in Köln jede Minute zählt. Deshalb bieten wir schnelle Termine und kommen direkt zu Ihrem Fahrzeug. Die gesamte Abwicklung übernehmen wir für Sie – zuverlässig und NRW-weit im Einsatz.',
    einsatzgebiete: [
      { city: 'Köln-Ehrenfeld', time: 'ca. 10 Min' },
      { city: 'Köln-Porz', time: 'ca. 20 Min' },
      { city: 'Köln-Nippes', time: 'ca. 15 Min' },
      { city: 'Leverkusen', time: 'ca. 20 Min' },
      { city: 'Bonn', time: 'ca. 30 Min' },
      { city: 'Bergisch Gladbach', time: 'ca. 25 Min' },
      { city: 'Troisdorf', time: 'ca. 25 Min' },
      { city: 'Hürth', time: 'ca. 15 Min' },
      { city: 'Brühl', time: 'ca. 20 Min' },
      { city: 'Frechen', time: 'ca. 15 Min' },
      { city: 'Erftstadt', time: 'ca. 30 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein KFZ-Gutachten in Köln?', a: 'Bei einem unverschuldeten Unfall übernimmt die gegnerische Versicherung die Kosten. Für Sie als Geschädigten ist das Gutachten kostenlos.' },
      { q: 'Wie schnell sind Sie in Köln vor Ort?', a: 'In den meisten Kölner Stadtteilen sind wir innerhalb von 15 bis 25 Minuten bei Ihnen. Termine oft noch am selben Tag möglich.' },
      { q: 'Brauche ich einen Anwalt nach dem Unfall?', a: 'Wir empfehlen die Hinzuziehung eines Anwalts und vermitteln Ihnen gerne einen. Auch die Anwaltskosten trägt die gegnerische Versicherung.' },
      { q: 'Kann ich den Gutachter frei wählen?', a: 'Ja, als Geschädigter haben Sie das Recht, Ihren eigenen unabhängigen Gutachter zu beauftragen. Die Kosten übernimmt die Gegenseite.' },
    ],
  },
  {
    slug: 'leverkusen',
    city: 'Leverkusen',
    metaTitle: 'KFZ Gutachter Leverkusen – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Leverkusen – schnelle Unfallgutachten, kostenlos für Geschädigte. Unabhängig und zuverlässig. Jetzt Termin vereinbaren!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Leverkusen und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'In Leverkusen und den umliegenden Gemeinden sind wir als Ihre unabhängigen Gutachter-Experten verlässlich erreichbar. Ob Schlebusch, Opladen oder Wiesdorf – wir kommen schnell und unkompliziert zu Ihrem Standort. Unser Ziel ist eine stressfreie Abwicklung: Sie melden sich, wir kümmern uns um den Rest. Von der Begutachtung bis zur Kommunikation mit der Versicherung übernehmen wir alles Nötige.',
    einsatzgebiete: [
      { city: 'Köln', time: 'ca. 20 Min' },
      { city: 'Bergisch Gladbach', time: 'ca. 15 Min' },
      { city: 'Langenfeld', time: 'ca. 15 Min' },
      { city: 'Solingen', time: 'ca. 25 Min' },
      { city: 'Düsseldorf', time: 'ca. 30 Min' },
      { city: 'Burscheid', time: 'ca. 15 Min' },
      { city: 'Troisdorf', time: 'ca. 30 Min' },
      { city: 'Bonn', time: 'ca. 40 Min' },
      { city: 'Monheim', time: 'ca. 20 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein Gutachten in Leverkusen?', a: 'Bei einem unverschuldeten Unfall ist das Gutachten für Sie kostenlos. Die gegnerische Versicherung kommt für alle Kosten auf.' },
      { q: 'Wie schnell kommen Sie nach Leverkusen?', a: 'In der Regel sind wir innerhalb von 25–40 Minuten in Leverkusen. Termine vereinbaren wir oft noch am gleichen Tag.' },
      { q: 'Wer übernimmt die Kosten nach einem Unfall?', a: 'Sämtliche Gutachterkosten trägt die Haftpflichtversicherung des Unfallverursachers. Sie zahlen nichts.' },
      { q: 'Wie läuft ein Gutachten ab?', a: 'Wir vereinbaren einen Termin, kommen zu Ihrem Fahrzeug, dokumentieren alle Schäden und erstellen das Gutachten innerhalb von 24–72 Stunden.' },
    ],
  },
  {
    slug: 'siegburg',
    city: 'Siegburg',
    metaTitle: 'KFZ Gutachter Siegburg – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Siegburg gesucht? Schnelle Unfallgutachten, kostenlos für Geschädigte. Ihr unabhängiger Sachverständiger vor Ort.',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Siegburg und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'Im Rhein-Sieg-Kreis rund um Siegburg sind wir als Ihre regionalen Gutachter-Experten bestens aufgestellt. Wir kennen die Gegebenheiten vor Ort und sind schnell erreichbar – ob im Zentrum von Siegburg oder in den Nachbargemeinden. Unser Versprechen: schnelle Termine, sorgfältige Arbeit und eine lückenlose Dokumentation, damit Sie Ihre Ansprüche gegenüber der Versicherung voll durchsetzen können.',
    einsatzgebiete: [
      { city: 'Sankt Augustin', time: 'ca. 10 Min' },
      { city: 'Troisdorf', time: 'ca. 10 Min' },
      { city: 'Hennef', time: 'ca. 15 Min' },
      { city: 'Lohmar', time: 'ca. 15 Min' },
      { city: 'Bonn', time: 'ca. 20 Min' },
      { city: 'Königswinter', time: 'ca. 20 Min' },
      { city: 'Bad Honnef', time: 'ca. 25 Min' },
      { city: 'Köln', time: 'ca. 35 Min' },
      { city: 'Much', time: 'ca. 25 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein KFZ-Gutachten in Siegburg?', a: 'Für Geschädigte ist das Gutachten kostenlos. Die gegnerische Versicherung übernimmt sämtliche Kosten für den unabhängigen Gutachter.' },
      { q: 'Wie schnell sind Sie in Siegburg vor Ort?', a: 'In Siegburg sind wir in der Regel innerhalb von 15 Minuten. Im gesamten Rhein-Sieg-Kreis bieten wir schnelle Termine an.' },
      { q: 'Wer übernimmt die Kosten nach einem Unfall?', a: 'Bei einem unverschuldeten Unfall zahlt die Haftpflichtversicherung des Verursachers alle Gutachterkosten.' },
      { q: 'Wie läuft ein Gutachten in Siegburg ab?', a: 'Rufen Sie uns an, wir kommen zum Fahrzeug, dokumentieren den Schaden und erstellen das Gutachten in 24–72 Stunden.' },
    ],
  },
  {
    slug: 'troisdorf',
    city: 'Troisdorf',
    metaTitle: 'KFZ Gutachter Troisdorf – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Troisdorf – schnelle Schadensbegutachtung vor Ort. Kostenlos für Geschädigte. Jetzt Termin vereinbaren!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Troisdorf und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'In Troisdorf und der direkten Umgebung stehen wir Ihnen als zuverlässige Gutachter-Experten zur Verfügung. Durch unsere Nähe zum Rhein-Sieg-Kreis erreichen wir Sie besonders schnell. Wir nehmen uns die Zeit für eine gründliche Begutachtung und setzen alles daran, dass Ihr Gutachten vollständig und rechtssicher ist. So sichern Sie Ihre Ansprüche – ohne eigenen Aufwand.',
    einsatzgebiete: [
      { city: 'Siegburg', time: 'ca. 10 Min' },
      { city: 'Sankt Augustin', time: 'ca. 10 Min' },
      { city: 'Bonn', time: 'ca. 20 Min' },
      { city: 'Köln-Porz', time: 'ca. 15 Min' },
      { city: 'Lohmar', time: 'ca. 15 Min' },
      { city: 'Hennef', time: 'ca. 20 Min' },
      { city: 'Niederkassel', time: 'ca. 15 Min' },
      { city: 'Köln', time: 'ca. 25 Min' },
      { city: 'Königswinter', time: 'ca. 25 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein Gutachten in Troisdorf?', a: 'Bei einem unverschuldeten Unfall entstehen Ihnen keine Kosten. Die gegnerische Versicherung bezahlt den Gutachter.' },
      { q: 'Wie schnell sind Sie in Troisdorf?', a: 'Wir sind in der Regel innerhalb von 20 Minuten in Troisdorf und können meist noch taggleich einen Termin anbieten.' },
      { q: 'Wer bezahlt den Gutachter?', a: 'Die Haftpflichtversicherung des Unfallverursachers trägt sämtliche Kosten. Für Sie als Geschädigten ist der Service kostenlos.' },
      { q: 'Kann ich Sie direkt kontaktieren?', a: 'Ja, per Telefon, WhatsApp oder Kontaktformular. Wir melden uns in der Regel innerhalb von 15 Minuten zurück.' },
    ],
  },
  {
    slug: 'sankt-augustin',
    city: 'Sankt Augustin',
    metaTitle: 'KFZ Gutachter Sankt Augustin – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Sankt Augustin – Ihr unabhängiger Sachverständiger vor Ort. Kostenlos für Geschädigte, schnelle Termine.',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Sankt Augustin und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'In Sankt Augustin bieten wir als Ihre Gutachter-Experten einen besonders schnellen Service. Durch die zentrale Lage im Rhein-Sieg-Kreis erreichen wir Sie in kürzester Zeit. Wir wissen, wie belastend ein Unfall sein kann, und sorgen dafür, dass die Schadensbewertung schnell und ohne Komplikationen abläuft. Von der ersten Kontaktaufnahme bis zur fertigen Dokumentation begleiten wir Sie persönlich.',
    einsatzgebiete: [
      { city: 'Siegburg', time: 'ca. 10 Min' },
      { city: 'Troisdorf', time: 'ca. 10 Min' },
      { city: 'Bonn', time: 'ca. 15 Min' },
      { city: 'Hennef', time: 'ca. 20 Min' },
      { city: 'Königswinter', time: 'ca. 15 Min' },
      { city: 'Niederkassel', time: 'ca. 15 Min' },
      { city: 'Köln', time: 'ca. 30 Min' },
      { city: 'Bad Honnef', time: 'ca. 25 Min' },
      { city: 'Lohmar', time: 'ca. 15 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein KFZ-Gutachten in Sankt Augustin?', a: 'Bei unverschuldetem Unfall kostenlos – die gegnerische Versicherung übernimmt alle Kosten für den unabhängigen Gutachter.' },
      { q: 'Wie schnell sind Sie in Sankt Augustin?', a: 'In Sankt Augustin sind wir in der Regel innerhalb von 15 Minuten. Termine oft noch am selben Tag verfügbar.' },
      { q: 'Wer übernimmt die Kosten?', a: 'Die Haftpflichtversicherung des Unfallverursachers kommt für sämtliche Gutachterkosten auf.' },
      { q: 'Wie läuft ein Gutachten ab?', a: 'Termin vereinbaren, Begutachtung vor Ort, Gutachten in 24–72 Stunden. Wir übernehmen die komplette Abwicklung für Sie.' },
    ],
  },
  {
    slug: 'alfter',
    city: 'Alfter',
    metaTitle: 'KFZ Gutachter Alfter – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Alfter – schnelle Unfallgutachten direkt vor Ort. Kostenlos für Geschädigte. Jetzt Kontakt aufnehmen!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Alfter und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'In Alfter und den angrenzenden Gemeinden im Vorgebirge sind wir besonders schnell bei Ihnen. Dank unserer Nähe zum Standort erreichen wir Sie oft schon innerhalb von 10 Minuten. Wir legen großen Wert auf eine persönliche Betreuung und sorgfältige Dokumentation – damit Sie sich nach dem Unfall keine Gedanken machen müssen. Ihre Ansprüche setzen wir konsequent durch.',
    einsatzgebiete: [
      { city: 'Bonn', time: 'ca. 10 Min' },
      { city: 'Bornheim', time: 'ca. 10 Min' },
      { city: 'Meckenheim', time: 'ca. 10 Min' },
      { city: 'Rheinbach', time: 'ca. 15 Min' },
      { city: 'Swisttal', time: 'ca. 15 Min' },
      { city: 'Euskirchen', time: 'ca. 25 Min' },
      { city: 'Köln', time: 'ca. 30 Min' },
      { city: 'Siegburg', time: 'ca. 25 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein Gutachten in Alfter?', a: 'Für Geschädigte ist unser Gutachten komplett kostenlos. Die Kosten übernimmt die gegnerische Versicherung.' },
      { q: 'Wie schnell kommen Sie nach Alfter?', a: 'Alfter liegt nur wenige Minuten von uns entfernt – wir sind in der Regel innerhalb von 10 Minuten vor Ort.' },
      { q: 'Wer übernimmt die Kosten?', a: 'Bei unverschuldetem Unfall zahlt die Haftpflichtversicherung des Verursachers. Für Sie entstehen keine Kosten.' },
      { q: 'Wie läuft die Schadensbegutachtung ab?', a: 'Wir kommen zu Ihrem Fahrzeug, dokumentieren den Schaden und erstellen das Gutachten innerhalb von 24–72 Stunden.' },
    ],
  },
  {
    slug: 'rheinbach',
    city: 'Rheinbach',
    metaTitle: 'KFZ Gutachter Rheinbach – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Rheinbach – professionelle Unfallgutachten, schnell vor Ort. Kostenlos für Geschädigte. Jetzt anrufen!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Rheinbach und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'In Rheinbach und der Voreifelregion sind wir regelmäßig im Einsatz. Unsere Gutachter-Experten kennen die Region bestens und sind kurzfristig verfügbar. Nach einem Unfall geht es um schnelles Handeln – und genau das bieten wir Ihnen. Wir kommen direkt zu Ihrem Fahrzeug, erstellen ein lückenloses Gutachten und kümmern uns um die Abwicklung mit der Versicherung.',
    einsatzgebiete: [
      { city: 'Meckenheim', time: 'ca. 10 Min' },
      { city: 'Swisttal', time: 'ca. 10 Min' },
      { city: 'Euskirchen', time: 'ca. 20 Min' },
      { city: 'Alfter', time: 'ca. 15 Min' },
      { city: 'Bonn', time: 'ca. 25 Min' },
      { city: 'Bornheim', time: 'ca. 20 Min' },
      { city: 'Bad Münstereifel', time: 'ca. 20 Min' },
      { city: 'Erftstadt', time: 'ca. 25 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein KFZ-Gutachten in Rheinbach?', a: 'Für Geschädigte bei unverschuldetem Unfall ist das Gutachten kostenlos. Alle Kosten trägt die gegnerische Versicherung.' },
      { q: 'Wie schnell sind Sie in Rheinbach?', a: 'Wir erreichen Rheinbach in der Regel innerhalb von 20–25 Minuten und bieten oft Termine am selben Tag an.' },
      { q: 'Wer bezahlt den Gutachter nach einem Unfall?', a: 'Die Haftpflichtversicherung des Unfallverursachers kommt für sämtliche Gutachterkosten auf.' },
      { q: 'Muss ich zur Begutachtung irgendwo hinfahren?', a: 'Nein, wir kommen zu Ihnen – egal ob zum Unfallort, nach Hause oder zur Werkstatt.' },
    ],
  },
  {
    slug: 'koenigswinter',
    city: 'Königswinter',
    metaTitle: 'KFZ Gutachter Königswinter – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Königswinter – unabhängige Unfallgutachten, schnell vor Ort. Kostenlos für Geschädigte. Jetzt Kontakt aufnehmen!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Königswinter und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'Am Fuße des Siebengebirges in Königswinter stehen wir Ihnen als zuverlässige Gutachter-Experten zur Seite. Ob in der Altstadt, in Oberpleis oder Thomasberg – wir kommen direkt zu Ihrem Fahrzeug. Unser Fokus liegt auf einer schnellen Verfügbarkeit und einer gründlichen Schadensbewertung, damit Sie Ihre Ansprüche vollständig geltend machen können.',
    einsatzgebiete: [
      { city: 'Bad Honnef', time: 'ca. 10 Min' },
      { city: 'Bonn', time: 'ca. 20 Min' },
      { city: 'Sankt Augustin', time: 'ca. 15 Min' },
      { city: 'Siegburg', time: 'ca. 20 Min' },
      { city: 'Hennef', time: 'ca. 20 Min' },
      { city: 'Troisdorf', time: 'ca. 25 Min' },
      { city: 'Bornheim', time: 'ca. 25 Min' },
      { city: 'Köln', time: 'ca. 40 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein Gutachten in Königswinter?', a: 'Für Geschädigte kostenlos. Die Kosten übernimmt die Haftpflichtversicherung des Unfallverursachers.' },
      { q: 'Wie schnell sind Sie in Königswinter vor Ort?', a: 'Wir sind in der Regel innerhalb von 30 Minuten in Königswinter und vergeben Termine häufig am selben Tag.' },
      { q: 'Wer zahlt den Gutachter?', a: 'Bei unverschuldetem Unfall die gegnerische Versicherung. Sie tragen keinerlei Kosten.' },
      { q: 'Wie läuft ein Gutachten ab?', a: 'Kontaktaufnahme, Vor-Ort-Begutachtung, fertiges Gutachten in 24–72 Stunden. Alles aus einer Hand.' },
    ],
  },
  {
    slug: 'bornheim',
    city: 'Bornheim',
    metaTitle: 'KFZ Gutachter Bornheim – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Bornheim – unabhängige Schadensbewertung direkt vor Ort. Kostenlos für Geschädigte. Jetzt Termin vereinbaren!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Bornheim und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'In Bornheim und dem Vorgebirge sind wir als unabhängige Gutachter-Experten regelmäßig vor Ort. Dank kurzer Anfahrtswege erreichen wir Sie schnell – ob in Roisdorf, Hersel oder Walberberg. Wir legen Wert auf eine persönliche Betreuung und gewissenhafte Arbeit, damit Ihre Schadensansprüche vollständig dokumentiert und durchsetzbar sind.',
    einsatzgebiete: [
      { city: 'Alfter', time: 'ca. 10 Min' },
      { city: 'Bonn', time: 'ca. 15 Min' },
      { city: 'Brühl', time: 'ca. 15 Min' },
      { city: 'Wesseling', time: 'ca. 15 Min' },
      { city: 'Swisttal', time: 'ca. 15 Min' },
      { city: 'Köln', time: 'ca. 25 Min' },
      { city: 'Meckenheim', time: 'ca. 15 Min' },
      { city: 'Siegburg', time: 'ca. 25 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein KFZ-Gutachten in Bornheim?', a: 'Für Geschädigte komplett kostenlos – die gegnerische Versicherung trägt sämtliche Gutachterkosten.' },
      { q: 'Wie schnell kommen Sie nach Bornheim?', a: 'In der Regel innerhalb von 15 Minuten. Termine meist noch am selben Tag möglich.' },
      { q: 'Wer übernimmt die Kosten nach einem Unfall?', a: 'Die Haftpflichtversicherung des Unfallverursachers bezahlt den unabhängigen Gutachter.' },
      { q: 'Kann ich den Gutachter frei wählen?', a: 'Ja, Sie haben das Recht, einen unabhängigen Gutachter zu beauftragen. Das empfehlen wir ausdrücklich.' },
    ],
  },
  {
    slug: 'meckenheim',
    city: 'Meckenheim',
    metaTitle: 'KFZ Gutachter Meckenheim – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Meckenheim – professionelle Unfallgutachten vor Ort. Kostenlos für Geschädigte, schnelle Termine. Jetzt anrufen!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Meckenheim und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'In Meckenheim und dem linksrheinischen Rhein-Sieg-Kreis sind wir als Ihre Gutachter-Experten schnell zur Stelle. Wir kennen die Struktur der Region und wissen, worauf es bei der Schadensbewertung ankommt. Verlassen Sie sich auf eine professionelle, zügige und kostenlose Abwicklung – wir kümmern uns um alles, damit Sie sich um nichts sorgen müssen.',
    einsatzgebiete: [
      { city: 'Rheinbach', time: 'ca. 10 Min' },
      { city: 'Alfter', time: 'ca. 10 Min' },
      { city: 'Wachtberg', time: 'ca. 10 Min' },
      { city: 'Bonn', time: 'ca. 20 Min' },
      { city: 'Swisttal', time: 'ca. 15 Min' },
      { city: 'Euskirchen', time: 'ca. 20 Min' },
      { city: 'Bornheim', time: 'ca. 15 Min' },
      { city: 'Köln', time: 'ca. 35 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein Gutachten in Meckenheim?', a: 'Für Sie als Geschädigten nichts. Die Kosten werden von der gegnerischen Versicherung übernommen.' },
      { q: 'Wie schnell sind Sie in Meckenheim?', a: 'Wir erreichen Meckenheim in der Regel innerhalb von 20 Minuten. Termine oft am gleichen Tag.' },
      { q: 'Wer bezahlt den Gutachter?', a: 'Die Haftpflichtversicherung des Unfallverursachers. Ihnen entstehen keine Kosten.' },
      { q: 'Wie läuft die Begutachtung ab?', a: 'Termin vereinbaren, Fahrzeug vor Ort begutachten, Gutachten in 24–72 Stunden erhalten.' },
    ],
  },
  {
    slug: 'bad-honnef',
    city: 'Bad Honnef',
    metaTitle: 'KFZ Gutachter Bad Honnef – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Bad Honnef – unabhängige Unfallgutachten, schnell vor Ort. Kostenlos für Geschädigte. Jetzt anrufen!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Bad Honnef und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'In Bad Honnef am Rhein und im südlichen Siebengebirge sind wir als unabhängige Gutachter-Experten für Sie da. Wir kommen zu Ihrem Fahrzeug – ob an der Insel Grafenwerth, in Rhöndorf oder Aegidienberg. Schnelle Erreichbarkeit und präzise Schadensdokumentation sind unser Markenzeichen, damit Sie nach einem Unfall schnell wieder Klarheit haben.',
    einsatzgebiete: [
      { city: 'Königswinter', time: 'ca. 10 Min' },
      { city: 'Unkel', time: 'ca. 10 Min' },
      { city: 'Bonn', time: 'ca. 25 Min' },
      { city: 'Sankt Augustin', time: 'ca. 20 Min' },
      { city: 'Siegburg', time: 'ca. 25 Min' },
      { city: 'Hennef', time: 'ca. 20 Min' },
      { city: 'Linz am Rhein', time: 'ca. 20 Min' },
      { city: 'Troisdorf', time: 'ca. 30 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein Gutachten in Bad Honnef?', a: 'Für Geschädigte kostenlos – die Haftpflichtversicherung des Verursachers übernimmt alle Kosten.' },
      { q: 'Wie schnell kommen Sie nach Bad Honnef?', a: 'Wir sind in der Regel innerhalb von 30 Minuten in Bad Honnef und bieten schnelle Terminvergabe.' },
      { q: 'Muss ich den Gutachter der Versicherung nehmen?', a: 'Nein, Sie dürfen Ihren Gutachter frei wählen. Wir sind unabhängig und vertreten ausschließlich Ihre Interessen.' },
      { q: 'Wie läuft ein Gutachten ab?', a: 'Kontaktaufnahme, Vor-Ort-Termin, Gutachten in 24–72 Stunden. Einfach und stressfrei.' },
    ],
  },
  {
    slug: 'bonn-duisdorf',
    city: 'Bonn-Duisdorf',
    metaTitle: 'KFZ Gutachter Bonn-Duisdorf – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Bonn-Duisdorf – schnelle Schadensbegutachtung vor Ort. Kostenlos für Geschädigte. Jetzt Termin vereinbaren!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Bonn-Duisdorf und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'Im Bonner Hardtberg und speziell in Duisdorf sind wir als Ihre Gutachter-Experten besonders schnell erreichbar. Ob Fahrzeugschaden auf der Rochusstraße oder im Gewerbegebiet – wir kommen direkt zu Ihnen. Unser Team arbeitet gründlich und effizient, damit Sie schnellstmöglich Ihr Gutachten erhalten und die Versicherung Ihre Ansprüche zügig reguliert.',
    einsatzgebiete: [
      { city: 'Bonn-Innenstadt', time: 'ca. 10 Min' },
      { city: 'Alfter', time: 'ca. 5 Min' },
      { city: 'Bornheim', time: 'ca. 15 Min' },
      { city: 'Meckenheim', time: 'ca. 15 Min' },
      { city: 'Rheinbach', time: 'ca. 20 Min' },
      { city: 'Swisttal', time: 'ca. 20 Min' },
      { city: 'Siegburg', time: 'ca. 25 Min' },
      { city: 'Köln', time: 'ca. 35 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein Gutachten in Bonn-Duisdorf?', a: 'Kostenlos für Geschädigte. Die gegnerische Versicherung übernimmt die Gutachterkosten vollständig.' },
      { q: 'Wie schnell kommen Sie nach Duisdorf?', a: 'In Bonn-Duisdorf und dem Hardtberg sind wir in wenigen Minuten vor Ort.' },
      { q: 'Wer übernimmt die Kosten?', a: 'Bei einem unverschuldeten Unfall zahlt die Haftpflichtversicherung des Verursachers.' },
      { q: 'Wie läuft die Begutachtung ab?', a: 'Termin vereinbaren, Fahrzeug begutachten, Gutachten in 24–72 Stunden – stressfrei und unkompliziert.' },
    ],
  },
  {
    slug: 'hennef',
    city: 'Hennef',
    metaTitle: 'KFZ Gutachter Hennef – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Hennef (Sieg) – unabhängige Gutachten, schnell vor Ort. Kostenlos für Geschädigte. Jetzt Kontakt aufnehmen!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Hennef und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'In Hennef an der Sieg und im östlichen Rhein-Sieg-Kreis stehen wir Ihnen als kompetente Gutachter-Experten zur Verfügung. Wir sind schnell erreichbar und kommen direkt zu Ihrem Fahrzeug – ob in der Innenstadt, in Uckerath oder in den umliegenden Ortsteilen. Verlassen Sie sich auf unsere Erfahrung für eine schnelle und vollständige Schadensdokumentation.',
    einsatzgebiete: [
      { city: 'Siegburg', time: 'ca. 15 Min' },
      { city: 'Sankt Augustin', time: 'ca. 20 Min' },
      { city: 'Eitorf', time: 'ca. 15 Min' },
      { city: 'Königswinter', time: 'ca. 20 Min' },
      { city: 'Bad Honnef', time: 'ca. 20 Min' },
      { city: 'Much', time: 'ca. 20 Min' },
      { city: 'Bonn', time: 'ca. 25 Min' },
      { city: 'Troisdorf', time: 'ca. 20 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein Gutachten in Hennef?', a: 'Für Geschädigte beim unverschuldeten Unfall kostenlos. Die gegnerische Versicherung trägt alle Kosten.' },
      { q: 'Wie schnell sind Sie in Hennef vor Ort?', a: 'Wir erreichen Hennef in der Regel innerhalb von 20–25 Minuten und bieten schnelle Termine.' },
      { q: 'Wer übernimmt die Gutachterkosten?', a: 'Die Haftpflichtversicherung des Unfallverursachers. Für Sie als Geschädigten fallen keine Kosten an.' },
      { q: 'Kann ich Sie auch am Wochenende erreichen?', a: 'Ja, wir bieten einen 24/7-Service und sind auch samstags und sonntags erreichbar.' },
    ],
  },
  {
    slug: 'mechernich',
    city: 'Mechernich',
    metaTitle: 'KFZ Gutachter Mechernich – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Mechernich – professionelle Unfallgutachten in der Eifel. Kostenlos für Geschädigte. Schnelle Termine!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Mechernich und der Eifelregion.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'In Mechernich und der Nordeifel sind wir als Ihre regionalen Gutachter-Experten zuverlässig erreichbar. Gerade im ländlichen Raum ist es wichtig, dass der Gutachter zu Ihnen kommt – und genau das tun wir. Ob in Kommern, Satzvey oder im Stadtkern, wir dokumentieren den Schaden sorgfältig vor Ort und sorgen für eine schnelle Regulierung durch die Versicherung.',
    einsatzgebiete: [
      { city: 'Euskirchen', time: 'ca. 15 Min' },
      { city: 'Bad Münstereifel', time: 'ca. 15 Min' },
      { city: 'Zülpich', time: 'ca. 20 Min' },
      { city: 'Kall', time: 'ca. 10 Min' },
      { city: 'Schleiden', time: 'ca. 20 Min' },
      { city: 'Blankenheim', time: 'ca. 25 Min' },
      { city: 'Nettersheim', time: 'ca. 15 Min' },
      { city: 'Rheinbach', time: 'ca. 30 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein KFZ-Gutachten in Mechernich?', a: 'Bei unverschuldetem Unfall kostenlos – die gegnerische Versicherung kommt für die Gutachterkosten auf.' },
      { q: 'Kommen Sie auch in die Eifel?', a: 'Ja, wir bedienen die gesamte Nordeifel von unserem Hauptstandort Euskirchen aus. Mechernich ist schnell erreichbar.' },
      { q: 'Wer übernimmt die Kosten?', a: 'Die Haftpflichtversicherung des Unfallverursachers. Ihnen entstehen keine Kosten.' },
      { q: 'Wie schnell erhalte ich mein Gutachten?', a: 'In der Regel innerhalb von 24–72 Stunden nach der Begutachtung vor Ort.' },
    ],
  },
  {
    slug: 'erftstadt',
    city: 'Erftstadt',
    metaTitle: 'KFZ Gutachter Erftstadt – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Erftstadt – unabhängige Unfallgutachten vor Ort. Kostenlos für Geschädigte, schnelle Verfügbarkeit. Jetzt anrufen!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Erftstadt und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'In Erftstadt und dem Rhein-Erft-Kreis setzen wir uns als Ihre Gutachter-Experten für eine faire Schadensbewertung ein. Ob in Lechenich, Liblar oder Gymnich – wir sind flexibel und schnell vor Ort. Die Region kennen wir gut, sodass wir bei der Bewertung von Wiederbeschaffungswerten den lokalen Markt berücksichtigen und Ihnen so die bestmögliche Grundlage für Ihre Ansprüche liefern.',
    einsatzgebiete: [
      { city: 'Brühl', time: 'ca. 15 Min' },
      { city: 'Hürth', time: 'ca. 15 Min' },
      { city: 'Weilerswist', time: 'ca. 10 Min' },
      { city: 'Euskirchen', time: 'ca. 25 Min' },
      { city: 'Köln', time: 'ca. 25 Min' },
      { city: 'Zülpich', time: 'ca. 20 Min' },
      { city: 'Bornheim', time: 'ca. 20 Min' },
      { city: 'Kerpen', time: 'ca. 15 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein KFZ-Gutachten in Erftstadt?', a: 'Für Geschädigte bei unverschuldetem Unfall komplett kostenlos. Die gegnerische Versicherung zahlt.' },
      { q: 'Wie schnell sind Sie in Erftstadt?', a: 'In der Regel innerhalb von 25 Minuten. Termine meist noch am selben Tag möglich.' },
      { q: 'Wer trägt die Kosten?', a: 'Die Haftpflichtversicherung des Unfallverursachers übernimmt sämtliche Gutachterkosten.' },
      { q: 'Wie läuft ein Gutachten ab?', a: 'Sie kontaktieren uns, wir kommen zum Fahrzeug, dokumentieren alles und liefern das Gutachten in 24–72 Stunden.' },
    ],
  },
  {
    slug: 'swisttal',
    city: 'Swisttal',
    metaTitle: 'KFZ Gutachter Swisttal – Kostenlos & Schnell | UnfallExperten NRW',
    metaDescription: 'KFZ Gutachter in Swisttal – professionelle Schadensbewertung vor Ort. Kostenlos für Geschädigte. Jetzt Kontakt aufnehmen!',
    heroSubline: 'Wir sind schnell bei Ihnen vor Ort – professionelle Unfallgutachten & Schadensbewertung in Swisttal und Umgebung.',
    trustText: 'Für Geschädigte kostenlos – die gegnerische Versicherung übernimmt in der Regel sämtliche Kosten. Kein Risiko, kein Stress.',
    description: 'In der Gemeinde Swisttal zwischen Bonn und Euskirchen sind wir als Ihre unabhängigen Gutachter-Experten schnell verfügbar. Ob in Heimerzheim, Odendorf oder Buschhoven – wir kommen zu Ihnen ans Fahrzeug. Kurze Wege, schnelle Termine und eine sorgfältige Dokumentation zeichnen unsere Arbeit aus. So bekommen Sie nach dem Unfall schnell Klarheit über Ihre Ansprüche.',
    einsatzgebiete: [
      { city: 'Rheinbach', time: 'ca. 10 Min' },
      { city: 'Meckenheim', time: 'ca. 10 Min' },
      { city: 'Alfter', time: 'ca. 15 Min' },
      { city: 'Euskirchen', time: 'ca. 20 Min' },
      { city: 'Bornheim', time: 'ca. 15 Min' },
      { city: 'Bonn', time: 'ca. 20 Min' },
      { city: 'Weilerswist', time: 'ca. 15 Min' },
      { city: 'Erftstadt', time: 'ca. 20 Min' },
    ],
    faqs: [
      { q: 'Was kostet ein Gutachten in Swisttal?', a: 'Für Geschädigte vollständig kostenlos. Die gegnerische Versicherung übernimmt die Kosten.' },
      { q: 'Wie schnell kommen Sie nach Swisttal?', a: 'Swisttal ist schnell erreichbar – in der Regel sind wir innerhalb von 20 Minuten bei Ihnen.' },
      { q: 'Wer bezahlt den Gutachter?', a: 'Die Haftpflichtversicherung des Verursachers. Für Sie entstehen keinerlei Kosten.' },
      { q: 'Wie läuft ein Gutachten ab?', a: 'Termin vereinbaren, Vor-Ort-Begutachtung, Gutachten in 24–72 Stunden – unkompliziert und schnell.' },
    ],
  },
];

export function getStandortBySlug(slug: string): StandortData | undefined {
  return STANDORTE.find(s => s.slug === slug);
}

export function getAllStandortSlugs(): string[] {
  return STANDORTE.map(s => s.slug);
}
